objects/Job_application__c.object
<CustomObject>
    <label>Job application</label>
    <nameField>
        <label>Job application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Review Resume</fullName>
                </value>
                <value>
                    <fullName>Phone Screen</fullName>
                </value>
                <value>
                    <fullName>Schedule Interviews</fullName>
                </value>
                <value>
                    <fullName>Extend and offer</fullName>
                </value>
                <value>
                    <fullName>Hired</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/RecruiterAppClass.cls
public class RecruiterAppClass {
    public static void reruiterAppMethod(List<Job_application__c> newList ){
        
        List <Task> newTask = new List<Task>();
        
        for(Job_application__c  jobApp: newList) {
            if(jobApp.Status__c == 'Rejected') {
                Task taskApp = new Task();
                taskApp.subject = 'Send Rejection Letter';
                taskApp.WhatId = jobApp.Id;
                taskApp.Description= 'Send rejection notification to the candidate';
                        taskApp.Status = 'Not Started';
               newTask.add(taskApp);
                
            }
            
        }
        
        if(!newTask.isEmpty()) {
            insert newTask;
        }
    }

}